/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.etapacurso.view;

import br.com.ifba.etapacurso.model.EtapaCurso;
import br.com.ifba.infrastructure.service.IFacade;
import br.com.ifba.infrastructure.support.StringUtil;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jonas Dias
 */
@Component 
public class TelaEdicaoEtapaCurso extends javax.swing.JFrame {

     @Autowired
     private IFacade facade;
     @Autowired @Lazy
     private TelaExibirEtapaCurso telaExibir;
     private EtapaCurso etapa;
     
     public TelaEdicaoEtapaCurso() {
          initComponents();
          super.setLocationRelativeTo(null);
     }
     
     // Define a etapa que será editada e mostra os dados nos campos da tela.
     public void setEtapa(EtapaCurso etapaCurso) {
          this.etapa = etapaCurso;
          
          txtNome.setText(etapaCurso.getNome());
          txtCargaHoraria.setText(Integer.toString(etapaCurso.getCargaHoraria()));
          txtPeriodo.setText(Integer.toString(etapaCurso.getPeriodo()));
          tlgConcluinte.getModel().setSelected(etapaCurso.isConcluinte());
     }
     
     private boolean validarCampos(EtapaCurso etapa) {
         StringUtil validacao = StringUtil.getInstance();
         if (validacao.isEmpty(etapa.getNome()) || 
                 validacao.isEmpty(Integer.toString(etapa.getCargaHoraria())) || 
                 validacao.isEmpty(Integer.toString(etapa.getPeriodo()))) {
            return false;
         }
        return true;
     }
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlDesignLinha = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblMsgDadosAtualizacao = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblLogoSad = new javax.swing.JLabel();
        tlgConcluinte = new javax.swing.JToggleButton();
        txtNome = new javax.swing.JTextField();
        txtCargaHoraria = new javax.swing.JTextField();
        txtPeriodo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContainer.setBackground(new java.awt.Color(220, 224, 230));
        pnlContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 76, 126), 3));

        pnlDesignLinha.setBackground(new java.awt.Color(43, 76, 126));

        javax.swing.GroupLayout pnlDesignLinhaLayout = new javax.swing.GroupLayout(pnlDesignLinha);
        pnlDesignLinha.setLayout(pnlDesignLinhaLayout);
        pnlDesignLinhaLayout.setHorizontalGroup(
            pnlDesignLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDesignLinhaLayout.setVerticalGroup(
            pnlDesignLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        btnVoltar.setBackground(new java.awt.Color(217, 217, 217));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblMsgDadosAtualizacao.setBackground(new java.awt.Color(0, 0, 0));
        lblMsgDadosAtualizacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMsgDadosAtualizacao.setText("INSIRA OS DADOS PARA ATUALIZAÇÃO");

        btnAtualizar.setBackground(new java.awt.Color(217, 217, 217));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblLogoSad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/sad/imagens/logo_sad.png"))); // NOI18N

        tlgConcluinte.setBackground(new java.awt.Color(217, 217, 217));
        tlgConcluinte.setText("Concluinte");

        txtNome.setBackground(new java.awt.Color(217, 217, 217));
        txtNome.setText("nome");

        txtCargaHoraria.setBackground(new java.awt.Color(217, 217, 217));
        txtCargaHoraria.setText("carga horária");

        txtPeriodo.setBackground(new java.awt.Color(217, 217, 217));
        txtPeriodo.setText("período");

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(pnlDesignLinha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblMsgDadosAtualizacao)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                        .addComponent(lblLogoSad)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(tlgConcluinte, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoSad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMsgDadosAtualizacao)
                .addGap(13, 13, 13)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tlgConcluinte, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDesignLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // Obtém os novos dados.
        String nome = txtNome.getText();
        boolean concluinte = tlgConcluinte.getModel().isSelected();
        int cargaHoraria, periodo;
        
        try {
            cargaHoraria = Integer.parseInt(txtCargaHoraria.getText());
            periodo = Integer.parseInt(txtPeriodo.getText());
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, error, 
                    "Carga horária e período aceitam apenas números inteiros!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Define os novos dados.
        this.etapa.setNome(nome);
        this.etapa.setCargaHoraria(cargaHoraria);
        this.etapa.setPeriodo(periodo);
        this.etapa.setConcluinte(concluinte);
        
        if (this.validarCampos(etapa) == false) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos e tente novamente!", 
                    "Preencha os Campos!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        /* 
            Tenta atualizar a etapa e depois mostra a tela de visualização com os novos dados.
            Caso ocorra um erro, mostra na tela.
        */
        try {
            if(JOptionPane.showConfirmDialog(null, "Deseja realmente editar " +
                       this.etapa.getNome() + "?", "Editar Dados", JOptionPane.DEFAULT_OPTION) == 0) {
                this.facade.updateEtapaCurso(this.etapa);
                this.telaExibir.atualizaTabela();
            }
            this.setVisible(false);
            this.telaExibir.setVisible(true);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error, 
                    "Erro ao editar!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
            this.setVisible(false);
            this.telaExibir.setVisible(true);
            this.telaExibir.atualizaTabela();
    }//GEN-LAST:event_btnVoltarActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(TelaEdicaoEtapaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(TelaEdicaoEtapaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(TelaEdicaoEtapaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(TelaEdicaoEtapaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>
        
          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new TelaEdicaoEtapaCurso().setVisible(true);
               }
          });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblLogoSad;
    private javax.swing.JLabel lblMsgDadosAtualizacao;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlDesignLinha;
    private javax.swing.JToggleButton tlgConcluinte;
    public javax.swing.JTextField txtCargaHoraria;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtPeriodo;
    // End of variables declaration//GEN-END:variables
}
